version: "3.9"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: >
      mlflow server
      --backend-store-uri /mlruns
      --default-artifact-root /mlruns
      --host 0.0.0.0

  trainer:
    build: .
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    command: python src/train_compare.py

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - trainer
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models